-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.links DROP CONSTRAINT IF EXISTS fk_id_user;



DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    nom character varying(50) NOT NULL,
    postnom character varying(50),
    username character varying(40) NOT NULL,
    password character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.links;

CREATE TABLE IF NOT EXISTS public.links
(
    id serial NOT NULL,
    url_shortened character varying NOT NULL,
    base_url character varying NOT NULL,
    qr_generated character varying NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    visitors bigint NOT NULL DEFAULT 0,
    id_user serial NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.sessions;

CREATE TABLE IF NOT EXISTS public.sessions
(
    id serial NOT NULL,
    sid character varying(255) NOT NULL,
    expires timestamp with time zone NOT NULL,
    data text NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.links
    ADD CONSTRAINT fk_id_user FOREIGN KEY (id_user)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;